### ISSUE TITLE
Configs Instructions

### ISSUE THREAD

**Issue by Ram-85** [herbstleyd/TwoTrees-Sapphire-Plus-Configs#1]
Thanks for your help in developing these Configs! While I am familiar with the Slicer profiles, I am not sure how to properly use the Config file. Can you please provide some instructions or details how to properly use this in new firmware? 

Much Appreciated!

**Comment by herbstleyd** [comment]
Hey, thank you! I am happy to help! 
I added a little "HowTo" in the README.md 
Hope that helps!
